version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.14
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests in parallel
          command: |
            circleci tests glob "tests/*.test.js" \
              | circleci tests split \
              | xargs -I {} npm test -- {}

workflows:
  test_workflow:
    jobs:
      - test
